Allow `create_exception!` to take a `dotted.module` to place the exception in a submodule.
