Reuses `std::io::Error` conversion code when converting `std::io::IntoInnerError` to `PyErr` 